name: memesgenerator
description: for creating funny memes

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  uuid: ^3.0.7
  google_fonts: ^4.0.3
  rxdart: ^0.27.7
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  image_picker: ^0.8.7
  path_provider: ^2.0.13
  screenshot: ^1.3.0
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3


flutter:

  uses-material-design: true

  assets:
    - assets/images/